### ISSUE TITLE
Status of the codebase

### ISSUE THREAD

**Issue by xguerin** [ujamjar/hardcaml-riscv#2]
Hey Andrew,

What is the status of that codebase? Can the processor be synthesized?
I am fooling around memory subsystems and I am looking for a RISC.

**Comment by andrewray** [comment]
I reckon maybe a couple of weeks work to get the basic 5 stage pipeline running C-code.  Possibly less - it was very nearly working when I was pulled away to work on something else.

There are various other bits including CSRs, interrupts, cache interfaces etc that are in varying states of readiness.

**Comment by xguerin** [comment]
Cool, I'll take a shot at it.
